---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hub-gitops-group-openshift
  namespace: uc2-openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: hub-gitops
        requeueAfterSeconds: 180
  template:
    metadata:
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
      labels:
        velero.io/exclude-from-backup: 'true'
      name: hub-gitops-group-openshift-{{name}}
    spec:
      destination:
        namespace: uc2-openshift-gitops
        server: "{{server}}"
      project: default
      sources:
        - path: policy-generator/openshift
          repoURL: https://github.com/nasx/policy-generator-gitops.git
          targetRevision: main
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - CreateNamespace=false
