---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
  - path: patch.yaml
    target:
      kind: MultiClusterHub
      name: multiclusterhub
      namespace: open-cluster-management
resources:
  - ../../base
