---
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: openshift-gitops-installplan-check
spec:
  remediationAction: inform
  severity: high
  object-templates-raw: |
    {{- $subscription := (lookup "operators.coreos.com/v1alpha1" "Subscription" "openshift-gitops" "openshift-gitops-operator") -}}
    {{- $installplans := (lookup "operators.coreos.com/v1alpha1" "InstallPlan" "openshift-gitops" "") -}}
    {{- range $installplans.items -}}
    {{- if has $subscription.status.installedCSV .spec.clusterServiceVersionNames -}}
    - complianceType: musthave
      objectDefinition:
        apiVersion: operators.coreos.com/v1alpha1
        kind: InstallPlan
        metadata:
          name: {{ .metadata.name }}
          namespace: openshift-gitops
        status:
          conditions:
            - status: "True"
              type: Installed
    {{- end }}
    {{- end }}
