---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
  - path: patch.yaml
    target:
      group: argoproj.io
      kind: ApplicationSet
      name: kyverno
      version: v1alpha1
resources:
  - ../../base
