---
{{- $rawInfrastructureName := "{{ (lookup \"config.openshift.io/v1\" \"Infrastructure\" \"\" \"cluster\").status.infrastructureName }}" }}
{{- $rawMachineSetName := (printf "%s-%s-%s" $rawInfrastructureName .Values.machineSet.role .Values.machineSet.nameSuffix) }}
{{- $rawTemplateName := (printf "%s-rhcos-%s-%s" $rawInfrastructureName .Values.machineSet.vmware.region .Values.machineSet.vmware.zone ) }}
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: '{{ $rawInfrastructureName }}'
  name: '{{ $rawMachineSetName }}'
  namespace: openshift-machine-api
spec:
  replicas: {{ .Values.machineSet.replicas }}
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: '{{ $rawInfrastructureName }}'
      machine.openshift.io/cluster-api-machineset: '{{ $rawMachineSetName }}'
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: '{{ $rawInfrastructureName }}'
        machine.openshift.io/cluster-api-machine-role: {{ .Values.machineSet.role }}
        machine.openshift.io/cluster-api-machine-type: {{ .Values.machineSet.role }}
        machine.openshift.io/cluster-api-machineset: '{{ $rawMachineSetName }}'
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/{{ .Values.machineSet.role }}: "" 
      providerSpec:
        value:
          apiVersion: vsphereprovider.openshift.io/v1beta1
          credentialsSecret:
            name: vsphere-cloud-credentials
          diskGiB: {{ .Values.machineSet.vmware.diskGiB }}
          kind: VSphereMachineProviderSpec
          memoryMiB: {{ .Values.machineSet.vmware.memoryMiB }}
          network:
            devices:
            - networkName: "{{ .Values.machineSet.vmware.networkName }}" 
          numCPUs: {{ .Values.machineSet.vmware.numCPUs }}
          numCoresPerSocket: {{ .Values.machineSet.vmware.numCoresPerSocket }}
          snapshot: ""
          template: '{{ $rawTemplateName }}'
          userDataSecret:
            name: worker-user-data
          workspace:
            datacenter: {{ .Values.machineSet.vmware.workspace.datacenter }}
            datastore: {{ .Values.machineSet.vmware.workspace.datastore }}
            folder: {{ .Values.machineSet.vmware.workspace.folder }}
            resourcepool: {{ .Values.machineSet.vmware.workspace.resourcepool }}
            server: {{ .Values.machineSet.vmware.workspace.server }}
