---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - literals:
      - alertmanager_enable_vct=false
      - alertmanager_storage_size=5Gi
      - alertmanager_storageclass=managed-csi
      - infra_nodes=true
      - prometheus_enable_vct=false
      - prometheus_storage_size=100Gi
      - prometheus_storageclass=managed-csi
    name: openshift-monitoring-policy-config
generatorOptions:
  disableNameSuffixHash: true
namespace: openshift-monitoring
