---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: hub-gitops
placementBindingDefaults:
  name: hub-gitops
policies:
  - manifests:
      - path: managed-clusters/prime
    name: hub-gitops-cluster-prime
  - manifests:
      - path: groups/openshift
    name: hub-gitops-group-openshift
policyDefaults:
  categories:
    - CM Configuration Management
  complianceType: musthave
  configurationPolicyAnnotations:
    policy.open-cluster-management.io/disable-templates: 'true'
  controls:
    - CM-2 Baseline Configuration
  copyPolicyMetadata: false
  namespace: uc2-openshift-gitops
  remediationAction: enforce
  severity: high
  standards:
    - NIST SP 800-53
policySets:
  - description: Specific Configurations for Cluster "prime"
    name: hub-gitops
    placement:
      placementPath: hub-placement.yaml
    policies:
      - hub-gitops-cluster-prime
      - hub-gitops-group-openshift
