---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: hub-openshift-gitops
placementBindingDefaults:
  name: hub-gitops
policies:
  - manifests:
      - path: operator/base
    name: hub-openshift-gitops-operator
  - consolidateManifests: false
    dependencies:
      - name: hub-openshift-gitops-operator
    manifests:
      - path: operator-check/base
    name: hub-openshift-gitops-operator-check
    remediationAction: inform
  - dependencies:
      - name: hub-openshift-gitops-operator-check
    manifests:
      - path: argocd/base
    name: hub-openshift-gitops-argocd
  - consolidateManifests: false
    dependencies:
      - name: hub-openshift-gitops-argocd
    manifests:
      - path: argocd-check/base
    name: hub-openshift-gitops-argocd-check
    remediationAction: inform
  - dependencies:
      - name: hub-openshift-gitops-argocd-check
    manifests:
      - path: argocd-post-install/base
    name: hub-openshift-gitops-argocd-post-install
policyDefaults:
  categories:
    - CM Configuration Management
  complianceType: musthave
  controls:
    - CM-2 Baseline Configuration
  namespace: hub-gitops
  remediationAction: enforce
  severity: high
  standards:
    - NIST SP 800-53
policySets:
  - description: "Hub Deployment of OpenShift GitOps/Argo CD"
    name: hub-openshift-gitops
    placement:
      placementPath: hub-placement.yaml
    policies:
      - hub-openshift-gitops-operator
      - hub-openshift-gitops-operator-check
      - hub-openshift-gitops-argocd
      - hub-openshift-gitops-argocd-check
      - hub-openshift-gitops-argocd-post-install
