---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
helmCharts:
- name: kyverno
  includeCRDs: true
  releaseName: kyverno
  repo: https://kyverno.github.io/kyverno/
  version: 3.2.5
  valuesFile: values-3.2.5.yaml
  namespace: kyverno
