---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
  - path: nodefeaturediscovery-patch.yaml
    target:
      group: nfd.openshift.io
      kind: NodeFeatureDiscovery
      name: nfd-instance
      version: v1
resources:
  - ../../base
