---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kyverno
  namespace: uc2-openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: kyverno-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      labels:
        velero.io/exclude-from-backup: 'true'
      name: kyverno-{{name}}
    spec:
      destination:
        namespace: kyverno
        server: '{{server}}'
      project: default
      sources:
        - helm:
            valuesObject:
              kyverno_release_name: kyverno-{{name}}
          path: charts/kyverno-openshift-helper
          repoURL: https://github.com/nasx/policy-generator-gitops.git
          targetRevision: main
        - chart: kyverno
          helm:
            valueFiles:
              - $values_source/kyverno-openshift/values/default.yaml
          repoURL: https://kyverno.github.io/kyverno/
          repositoryType: helm
          targetRevision: 3.2.6
        - ref: values_source
          repoURL: https://github.com/nasx/policy-generator-gitops.git
          targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
          - ServerSideApply=true
