---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kyverno:cleanup-controller
  labels:
    app.kubernetes.io/component: cleanup-controller
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/part-of: kyverno
    app.kubernetes.io/version: v1.12.5
  namespace: kyverno
rules:
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - create
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - delete
      - get
      - list
      - update
      - watch
    resourceNames:
      - kyverno-cleanup-controller.kyverno.svc.kyverno-tls-ca
      - kyverno-cleanup-controller.kyverno.svc.kyverno-tls-pair
  - apiGroups:
      - ''
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
    resourceNames:
      - kyverno
      - kyverno-metrics
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - delete
      - get
      - patch
      - update
    resourceNames:
      - kyverno-cleanup-controller
