---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: kyverno-cleanup-ephemeral-reports
  namespace: kyverno
  labels:
    app.kubernetes.io/component: cleanup
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/part-of: kyverno
    app.kubernetes.io/version: v1.12.5
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        metadata:
        spec:
          serviceAccountName: kyverno-cleanup-jobs
          containers:
          - name: cleanup
            image: "bitnami/kubectl:1.28.5"
            imagePullPolicy: 
            command:
            - /bin/bash
            - -c
            - |
              set -euo pipefail
              COUNT=$(kubectl get ephemeralreports.reports.kyverno.io -A | wc -l)
              if [ "$COUNT" -gt 10000 ]; then
                echo "too many ephemeralreports found ($COUNT), cleaning up..."
                kubectl delete ephemeralreports.reports.kyverno.io -A --all
              else
                echo "($COUNT) reports found, no clean up needed"
              fi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
              privileged: false
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              seccompProfile:
                type: RuntimeDefault
          restartPolicy: OnFailure
